### ISSUE TITLE
Dependency tersmitten.locales fails

### ISSUE THREAD

**Issue by jchonig** [mikolak-net/ansible-raspi-config#15]
`- downloading role 'raspi-config', owned by mikolak
- downloading role from https://github.com/mikolak-net/ansible-raspi-config/archive/1.2.0.tar.gz
- extracting mikolak.raspi-config to /Users/jch/Documents/ansible-things/galaxy-roles/mikolak.raspi-config
- mikolak.raspi-config (1.2.0) was installed successfully
- adding dependency: tersmitten.locales (v1.0.16)
- adding dependency: Stouts.hostname (1.1.0)
- downloading role 'locales', owned by tersmitten
 [WARNING]: - tersmitten.locales was NOT installed successfully: - sorry, tersmitten.locales was not found on https://galaxy.ansible.com.`

**Comment by jchonig** [comment]
https://github.com/Oefenweb/ansible-locales/issues/11

**Comment by eberkund** [comment]
I am having the same problem, does the dependency name just need to changed?

**Comment by mikolak-net** [comment]
@eberkund : no, I just neeed to move my a**e and review the issue :).

**Comment by eberkund** [comment]
@mikolak-net I have submitted a PR.

**Comment by colin-nolan** [comment]
I've reviewed and merged the fix. I am not sure why Ansible Galaxy is deciding it's a good idea to break things!

**Comment by eberkund** [comment]
The code from the GitHub repository works now but the version still needs to be bumped on Ansible Galaxy

**Comment by colin-nolan** [comment]
@mikolak-net on that one. I would suggest switching your dependency to GitHub rather than Galaxy.

**Comment by eberkund** [comment]
@colin-nolan Thanks for the tip, I will do that

**Comment by mikolak-net** [comment]
Solved in 1.2.1, available on Galaxy.

Note that the role **has been renamed to `mikolak-net.raspi_config`** (instead of `mikolak.raspi-config`).

This rename has been enforced by the Galaxy importer unfortunately, sorry about the inconvenience :(.
